(function(g){var window=this;var e3=function(a){var b={languageCode:a.languageCode,languageName:a.languageName,displayName:g.tE(a),kind:a.kind,name:a.name,id:a.id,is_servable:a.u,is_default:a.isDefault,is_translateable:a.isTranslateable,vss_id:a.vssId};a.translationLanguage&&(b.translationLanguage=a.translationLanguage);return b},f3=function(a){return a.translationLanguage?a.translationLanguage.languageCode:a.languageCode},UCa=function(a,b){var c=new g.sE;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.u=a.u;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;return c},VCa=function(){this.B=[];
this.u=[]},g3=function(a,b){switch(b.kind){case "asr":WCa(b,a.B);
break;default:WCa(b,a.u)}},WCa=function(a,b){g.jb(b,function(c){return c?a.toString()===c.toString():!1})||b.push(a)},h3=function(){g.B.call(this);
this.B=new VCa;this.D=[]},i3=function(a,b,c){h3.call(this,a);
this.audioTrack=c;this.u=null;this.D=b.cv},j3=function(){this.segments=[]},XCa=function(a,b){var c=g.Ab(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.qb(a.segments,c),g.qb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.xb(a.segments,c,0,b),g.xb(a.segments,c+1,0,b)))},k3=function(a,b,c,d,e,f){g.B.call(this);
this.policy=a;this.player=b;this.W=c;this.I=d;this.F=e;this.N=f;this.P=this.player.T();this.D=new j3;this.B=this.C=this.u=null;this.K=new g.H(this.tC,1E3,this);this.events=new g.Pr(this);g.C(this,this.K);g.C(this,this.events);this.events.R(b,"SEEK_COMPLETE",this.UC);this.UC();this.tC()},YCa=function(a,b){var c=g.Av(b,a.policy,{}).cd(),d={format:"RAW",
withCredentials:!0};a.F&&(d.responseType="arraybuffer");a.B=g.rr(c,d,3,100).then(function(e){a:{a.la();if(a.C){var f=!(a.F?e.response:e.responseText)||400<=e.status,h=g.yz(e);if(h){e=g.Av(a.C,a.policy,{});f=a.C;g.wv(f.B,e,h);f.requestId=e.get("req_id");YCa(a,a.C);break a}f||null==a.I||(h=a.C.u[0],a.F?a.I(e.response,1E3*(h.startTime+a.player.fc())):a.I(e.responseText,1E3*(h.startTime+a.player.fc())))}a.C=null;a.B=null}});
a.C=b;XCa(a.D,a.C.u[0].B)},l3=function(a,b){h3.call(this,b.T());
this.ma=a;this.J=b;this.u=null;this.C=!1;this.F=g.hC(this.J.T())&&!this.ma.isManifestless},ZCa=function(a,b){var c=[],d;
for(d in a.ma.u)if(a.ma.u.hasOwnProperty(d)){var e=a.ma.u[d];if(g.jX(e,b||null)){var f="en",h="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind;c.push(new g.sE({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},$Ca=function(a,b){return null!=b&&b in a.ma.u?a.ma.u[b]:null},aDa=function(a,b,c){var d=[],e;
for(e in a.ma.u)if(a.ma.u.hasOwnProperty(e)){var f=a.ma.u[e];if(g.jX(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},m3=function(a,b,c,d,e){h3.call(this,e||null);
this.videoId=b;this.TB=d;this.F={};this.u=null;b=c||g.Xp(a).hl||"";b=b.split("_").join("-");this.C=g.Zp(a,{hl:b})},n3=function(a,b,c,d,e,f,h){var l={};
g.Wa(l,b);g.Wa(l,a.params);g.Wa(l,c);var m={};g.Wa(m,b.oc);a.params.oc&&g.Wa(m,a.params.oc);g.Wa(m,c.oc);l.oc=m;g.V.call(this,{G:"div",L:"caption-window",U:{id:"caption-window-"+a.id,dir:1===l.u?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:l.lang},S:[{G:"span",L:"captions-text",U:{style:"word-wrap: normal; display: block;"}}]});this.F=[];this.Y=!1;this.B=a;this.fa=this.ba=null;this.playerWidth=e;this.playerHeight=f;this.experiments=h;this.I=null;this.maxWidth=.96*e;this.Ia=.96*f;this.u=l;
this.Za=c;this.D=this.ga("captions-text");this.Ra=""!==this.D.style.getPropertyValue("box-decoration-break")||""!==this.D.style.getPropertyValue("-webkit-box-decoration-break");this.ea=d/360*16;this.type=0;this.oa=this.ea*bDa(m);a=new g.Vr(this.element,!0);g.C(this,a);a.subscribe("dragstart",this.FK,this);a.subscribe("dragmove",this.EK,this);a.subscribe("dragend",this.DK,this);this.Fa=this.xa=0;b="";this.u.windowOpacity&&(a=g.U0(this.u.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.u.windowOpacity+
")");a={"background-color":b,display:!1===this.u.isVisible?"none":"","text-align":cDa[this.u.textAlign]};this.Ra&&(a["border-radius"]=b?this.oa/8+"px":"");if(this.C=2===this.B.params.u||3===this.B.params.u)b=this.element,c="vertical-rl",1===this.u.C&&(c="vertical-lr"),g.ye&&(c="vertical-lr"===c?"tb-lr":"tb-rl"),g.F(b,"-o-writing-mode",c),g.F(b,"-webkit-writing-mode",c),g.F(b,"writing-mode",c),g.F(b,"text-orientation","upright"),g.I(b,"ytp-vertical-caption"),3===this.B.params.u&&(g.F(b,"text-orientation",
""),g.F(b,"transform","rotate(180deg)"));g.F(this.element,a);switch(this.u.Hg){case 0:case 1:case 2:g.I(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.I(this.element,"ytp-caption-window-bottom")}},bDa=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},dDa=function(a,b){var c={},d=b.background?b.background:a.u.oc.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.u.oc.backgroundOpacity;d=g.U0(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Ra&&(c["box-decoration-break"]="clone",c["border-radius"]=a.oa/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.ea*bDa(b)+"px";d=1;e=b.color||a.u.oc.color;if(b.color||null!=b.textOpacity)e=g.U0(e),d=null==b.textOpacity?a.u.oc.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.hv&&(h=e=b.hv);var l=a.ea/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=r;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.ak()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.u.oc.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Yg&&(c["font-style"]="italic");
b.underline&&(c["text-decoration"]="underline");b.gJ&&(c.visibility="hidden");1===b.QB&&a.C&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.lC||g.mC,3===a.B.params.u?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.rh||2===b.rh||3===b.rh||4===b.rh||5===b.rh)if(g.lC)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.rh){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},eDa=function(a){a.I=g.Fe("SPAN");
g.F(a.I,{display:"block"});g.I(a.I,"caption-visual-line");a.D.appendChild(a.I)},fDa=function(a,b){var c=g.Fe("SPAN");
g.F(c,{display:"inline-block","white-space":"pre-wrap"});g.F(c,dDa(a,b));c.classList.add("ytp-caption-segment");a.I.appendChild(c);c.previousElementSibling&&(g.F(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.F(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},gDa=function(a,b,c){a.Y=a.Y||!!c;
var d={};g.Wa(d,a.u.oc);g.Wa(d,c||b.u);g.Wa(d,a.Za.oc);(c=!a.I)&&eDa(a);for(var e=a.ba&&a.fa&&g.Yb(d,a.fa)?a.ba:fDa(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(eDa(a),e=fDa(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.Ge(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.lC||!g.sg(n.children[2],"text-emphasis")||(m=a.C?"padding-right":"padding-top",g.sg(n.children[2],"text-emphasis-position")&&(m=a.C?"padding-left":"padding-bottom"),
g.Ae?g.F(e,m,"1em"):g.F(e,m,"0.5em")))}a.fa=d;a.ba=e;a.F.push(b)},o3=function(a,b,c,d,e,f,h){n3.call(this,a,b,c,d,e,f,h);
this.type=1},p3=function(a,b,c,d,e,f,h){n3.call(this,a,b,c,d,e,f,h);
this.type=2;this.K=[];this.W=this.P=this.ha=0;this.X=NaN;this.Ma=0;this.jb=null;this.ka=new g.H(this.JO,433,this);g.I(this.element,"ytp-caption-window-rollup");g.C(this,this.ka);g.F(this.element,"overflow","hidden")},hDa=function(a,b){return(a.C?b.offsetHeight:b.offsetWidth)+1},iDa=function(a){if(isNaN(a.X)){var b=a.u.Gj;
if(b){var c=g.Fe("SPAN");g.Ne(c,"\u2013".repeat(b));g.F(c,dDa(a,a.u.oc));a.D.appendChild(c);a.X=c.offsetWidth;a.D.removeChild(c)}else a.X=0}return a.X},jDa=function(a,b){if(!b)return"";
a.C&&1!==a.B.params.C&&(b*=-1);return"translate"+(a.C?"X":"Y")+"("+b+"px)"},kDa=function(a){a.K=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.B.params.B,c=0,d=0,e=a.K.length-1;c<b&&-1<e;){var f=a.K[e];d+=a.C?f.offsetWidth:f.offsetHeight;c++;e--}a.K.length<b&&(d*=b/a.K.length);a.P=d;a.W=Math.max(iDa(a),a.Ma,hDa(a,a.D))},lDa=function(a,b){kDa(a);
var c=a.K.reduce(function(e,f){return(a.C?f.offsetWidth:f.offsetHeight)+e},0);
c=a.P-c;if(c!==a.ha){var d=0<c&&0===a.ha;b||isNaN(c)||d||(g.I(a.element,"ytp-rollup-mode"),a.ka.ub());g.F(a.D,"transform",jDa(a,c));a.ha=c}kDa(a)},q3=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.oD.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.u=h},r3=function(a,b,c,d,e){g.oD.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.u=[]},mDa=function(a){var b="_"+s3++;
return new r3(0,0x8000000000000,0,b,a)},oDa=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.Sc){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=nDa(l.textContent,n.textContent,p.textContent,f.textContent,h);return new q3(a,b,e,c,l,d,m)}switch(m.Sc){case 9:case 10:m.rh=1;break;case 11:m.rh=2;break;case 12:m.rh=3;break;case 13:m.rh=4;break;case 14:m.rh=5}return new q3(a,b,e,c,l.textContent||"",d,m)},nDa=function(a,b,c,d,e){var f=g.ak(),h=
f?g.Fe("DIV"):g.Fe("RUBY"),l=g.Fe("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.Fe("DIV"):g.Fe("RP");a.textContent=b;h.appendChild(a);b=f?g.Fe("DIV"):g.Fe("RT");b.textContent=c;h.appendChild(b);c=e.Sc;if(10===c||11===c||12===c||13===c||14===c)if(g.F(b,"text-emphasis-style","filled circle"),g.F(b,"text-emphasis-color","currentcolor"),g.F(b,"webkit-text-emphasis","filled circle"),11===e.Sc||13===e.Sc)g.F(b,"webkit-text-emphasis-position","under left"),g.F(b,"text-emphasis-position","under left");c=!0;if(4===e.Sc||7===e.Sc||12===e.Sc||14===
e.Sc)g.F(h,"ruby-position","over"),g.F(h,"-webkit-ruby-position","before");else if(5===e.Sc||6===e.Sc||11===e.Sc||13===e.Sc)g.F(h,"ruby-position","under"),g.F(h,"-webkit-ruby-position","after"),c=!1;e=f?g.Fe("DIV"):g.Fe("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.F(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.F(f,"display","none"),f=f.nextElementSibling,g.F(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",left:"50%",
transform:"translateX(-50%)",width:"400%"}),g.F(h.lastElementChild,"display","none"),d?(g.F(h,"padding-top","0.6em"),g.F(f,"top","0")):(g.F(h,"padding-bottom","0.6em"),g.F(f,"bottom","0")));return h},t3=function(){g.B.apply(this,arguments)},u3=function(a){t3.call(this);
this.I=a;this.D={};this.P={};this.W={};this.F="_"+s3++;this.N={};this.B=this.u=null;this.K=!0},v3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return Number(c)},w3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"===c},x3=function(a,b){var c=v3(a,b);
return void 0!==c?c:null},z3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return y3.test(c),c},pDa=function(a,b){var c={},d=b.getAttribute("ws");
g.Wa(c,d?a.W[d]:a.I);d=x3(b,"mh");null!=d&&(c.Wm=d);d=x3(b,"ju");null!=d&&(c.textAlign=d);d=x3(b,"pd");null!=d&&(c.u=d);d=x3(b,"sd");null!=d&&(c.C=d);d=z3(b,"wfc");null!=d&&(c.windowColor=d);d=v3(b,"wfo");void 0!==d&&(c.windowOpacity=d/255);return c},qDa=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Wa(c,a.P[d]);d=x3(b,"ap");null!=d&&(c.Hg=d);d=v3(b,"cc");null!=d&&(c.Gj=d);d=v3(b,"ah");null!=d&&(c.Tf=d);d=v3(b,"rc");null!=d&&(c.B=d);d=v3(b,"av");null!=d&&(c.wh=d);return c},rDa=function(a,b,c,d){var e={};
g.Wa(e,qDa(a,b));g.Wa(e,pDa(a,b));d?g.Yb(e,a.I)?(d=a.F,e=a.I):d="_"+s3++:d=b.getAttribute("id")||"_"+s3++;a=v3(b,"t")+c;b=v3(b,"d")||0x8000000000000;if(2===e.u||3===e.u)c=e.B,e.B=e.Gj,e.Gj=c;return new r3(a,b,0,d,e)},A3=function(a){t3.call(this);
this.I=a;this.u=new Map;this.D=new Map;this.F=new Map;this.B=new Map},B3=function(a){a=g.be(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},sDa=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.D.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.F.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.B=a);b=b.ccColCount;void 0!==b&&(f.Gj=b);if(2===f.u||3===f.u)b=f.B,f.B=f.Gj,f.Gj=b;return new r3(c,d,0,e,f)},D3=function(){this.C=this.time=this.mode=this.B=0;
this.D=new C3(this);this.F=new C3(this);this.u=[];this.clear()},uDa=function(a,b,c){if(255===a&&255===b||!a&&!b)return{Lk:a,
Dj:b,result:0};a=tDa[a];b=tDa[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.isValid()&&c.Dj===d;if(d)return{Lk:a,Dj:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Lk:a,Dj:b,result:2};return{Lk:a,Dj:b,result:3}},wDa=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.C&&a.reset(),a.D.u.clear(),a.F.u.clear()):(a.C=0,vDa(a.D,b,c,d))},xDa=function(a,b){a.u.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.q(a.u),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?wDa(a,d.nA,d.oA,b):1===d.type&&a.B&496&&vDa(a.F,d.nA,d.oA,b);a.u.length=0},E3=function(){this.type=0},F3=function(){this.state=this.Dj=this.Lk=0},yDa=function(){this.timestamp=this.u=0},G3=function(a){this.F=a;
this.C=[];this.u=this.B=this.row=0;this.style=new E3;for(a=this.D=0;15>=a;a++){this.C[a]=[];for(var b=0;32>=b;b++)this.C[a][b]=new yDa}},H3=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.F.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var r=a.C[m][p];
if(0!==r.u){0===c&&(c=m,d=p);n=String.fromCharCode(r.u);var t=r.timestamp;t<e&&(e=t);r.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===r.u||32===p)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.F(c,d,e,l,f)}else for(d=c=0,f=e=a.F.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(p=a.C[h][m],r=p.u,0!==r&&(0===c&&(c=h,d=m),n=String.fromCharCode(r),t=p.timestamp,t<=e&&(e=t),l+=n,p.reset()),32===m||0===r)l&&b.F(c,d,e,f,l),e=f,l="",d=c=0},DDa=function(a,b){switch(a){case 0:return zDa[(b&127)-32];
case 1:return ADa[b&15];case 2:return BDa[b&31];case 3:return CDa[b&31]}return 0},I3=function(a){return a.C[a.row][a.B]},J3=function(a,b,c){2<=b&&1<a.B&&(--a.B,I3(a).u=0);
var d=I3(a);d.timestamp=a.F.time+0;d.u=DDa(b,c);32>a.B&&a.B++},EDa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.C[b+e][f],l=a.C[c+e][f];
h.u=l.u;h.timestamp=l.timestamp}},K3=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.C[b+d][e].reset()},L3=function(a){a.row=0<a.u?a.u:1;
a.B=1;K3(a,0,15)},M3=function(a){this.C=a;
this.F=0;this.style=new E3;this.I=new G3(this.C);this.K=new G3(this.C);this.text=new G3(this.C);this.B=this.I;this.D=this.K;this.u=this.B},N3=function(a,b,c){var d=a.B,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.u||(H3(d,c),L3(a.B),L3(a.D),d.row=15,d.u=b,e=!0)}a.style.set(3);a.u=d;a.u.style=a.style;a.C.mode=1<<d.D;e?d.B=1:d.u!==b&&(d.u>b?(H3(d,c),K3(d,d.row-d.u,b)):d.row<b&&(b=d.u),d.u=b)},FDa=function(a){a.style.set(1);
a.u=a.D;a.u.u=0;a.u.style=a.style;a.C.mode=1<<a.u.D},GDa=function(a){a.style.set(4);
a.u=a.text;a.u.style=a.style;a.C.mode=1<<a.u.D},C3=function(a){this.B=a;
this.F=0;this.C=new M3(this.B);this.I=new M3(this.B);this.u=new F3;this.D=this.C},vDa=function(a,b,c,d){a.u.update();
b=uDa(b,c,a.u);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Lk;c=b.Dj;if(32<=e||!e)a.B.mode&a.B.B&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.D.u,b&96&&J3(a,0,b),c&96&&J3(a,0,c),0!==b&&0!==c&&3===a.style.type&&H3(a,d));else if(e&16)a:if(!a.u.matches(e,c)&&(b=a.u,b.Lk=e,b.Dj=c,b.state=2,b=e&8?a.I:a.C,a.D=b,a.B.mode=1<<(a.F<<2)+(b.F<<1)+(4===b.style.type?1:0),(a.B.mode|1<<(a.F<<2)+(b.F<<1)+(4!==b.style.type?1:0))&a.B.B))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.u;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.u&&(d=c.u,d===c.row))break;var f=1+c.row-c.u,h=1+d-c.u;EDa(c,h,f,c.u);b=f;e=c.u;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));K3(c,b,e)}}c.row=d;c.B=a+1}else switch(e&7){case 1:switch(c&112){case 32:J3(b.u,0,32);break a;case 48:57===c?(d=b.u,I3(d).u=0,32>d.B&&d.B++):J3(b.u,1,c&15)}break;case 2:c&32&&J3(b.u,2,c&31);break;case 3:c&32&&J3(b.u,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:FDa(b);
break;case 33:d=b.u;1<d.B&&(--d.B,I3(d).u=0);break;case 36:d=b.u;b=I3(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.C[a][c]===b){for(;32>=c;c++)d.C[a][c].reset();break}break;case 37:N3(b,2,d);break;case 38:N3(b,3,d);break;case 39:N3(b,4,d);break;case 40:J3(b.u,0,32);break;case 41:b.style.set(2);b.u=b.B;b.u.u=0;b.u.style=b.style;b.C.mode=1<<b.u.D;break;case 42:d=b.text;d.u=15;d.style.set(4);L3(d);GDa(b);break;case 43:GDa(b);break;case 44:a=b.B;switch(b.style.get()){case 1:case 2:case 3:H3(a,d)}K3(a,
0,15);break;case 45:b:{a=b.u;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.B=1;break b}case 3:}2>a.u&&(a.u=2,a.row<a.u&&(a.row=a.u));b=a.row-a.u+1;H3(a,d);EDa(a,b,b+1,a.u-1);K3(a,a.row,1)}break;case 46:K3(b.D,0,15);break;case 47:H3(b.B,d),b.D.updateTime(b.C.time+0),d=b.D,b.D=b.B,b.B=d,FDa(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.u,32<(d.B+=c&3)&&(d.B=32)}}},HDa=function(){},O3=function(a,b,c){this.N=a;
this.K=c;this.version=this.I=this.D=this.u=0;this.B=new DataView(this.N);this.C=[]},P3=function(a){var b=a.u;
a.u+=1;return a.B.getUint8(b)},Q3=function(a){var b=a.u;
a.u+=4;return a.B.getUint32(b)},R3=function(a,b){t3.call(this);
this.B=a;this.D=b;this.track="CC3"===this.D.languageName?4:0;this.u=new D3;this.u.B=1<<this.track},S3=function(a){if("string"===typeof a)return!1;
a=new O3(a,8,0);return IDa(a)},IDa=function(a){if(!(a.u<a.B.byteLength)||1380139777!==Q3(a))return!1;
a.version=P3(a);if(1<a.version)return!1;P3(a);P3(a);P3(a);return!0},T3=function(){t3.call(this)},JDa=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.Yg=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(3===p.nodeType)p=new q3(b,c,d,e.id,p.nodeValue,f||0<n,g.Wb(l)?void 0:l),m.push(p),e.u.push(p);else{var r={};g.Wa(r,l);JDa(a,b,c,d,e,!0,p,r,m)}}},U3=function(a){var b=a.split(":");
a=0;b=g.q(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},KDa=function(a,b,c,d){d=Object.assign({Wm:0},d);
return new r3(a,b,c,"_"+s3++,d)},V3=function(a){g.B.call(this);
this.B=a;this.u=null},MDa=function(a){var b={};
if(a=f3(a))b.lang=a,LDa.test(a)&&(b.u=1);return b},Y3=function(a){g.vS.call(this,a);
this.J=a;this.C=this.J.T();this.videoData=this.J.getVideoData();this.Ma=g.yG(this.J);this.D={oc:{}};this.I={oc:{}};this.X=[];this.P={};this.ka={};this.ba=!1;this.Fa=g.Qva(this.videoData,this.J);this.Ra=!!this.videoData.captionTracks.length;this.Za=!!this.videoData.Zn;this.ya="3"===this.C.controlsType;this.B=this.K=this.N=this.ha=this.xa=null;this.oa=new V3(this.C);this.u=null;this.fa=new g.Pr(this);var b=null,c=g.io("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.Sn(c));this.storage=b;
b=a.app.F;c=!(!b||!b.cq());this.Ia=!(!b||!b.Ul());this.F=this.ya&&c&&!this.Fa;this.W=!this.F&&this.ya&&this.Ia&&this.Fa;g.C(this,this.oa);this.F?this.ea=this.Y=null:(this.Y=new g.qn(this.gG,void 0,this),g.C(this,this.Y),this.ea=new g.H(this.gQ,2E3,this),g.C(this,this.ea));g.C(this,this.fa);this.F||this.fa.R(a,"resize",this.Ry);this.fa.R(a,"onPlaybackAudioChange",this.wM);this.fa.R(a,g.rD("captions"),this.GK,this);this.fa.R(a,g.sD("captions"),this.HK,this);W3(this,X3(this,"display-settings")||{})},
Z3=function(a){if(1===a.C.Ci||1===a.videoData.Ci||"alwayson"===g.wF(a.videoData,"yt:cc"))return!0;
if(2===a.C.Ci){var b=X3(a,"module-enabled");if(null!=b)return!!b}if(a.videoData.captionTracks.length)var c=a.player.getAudioTrack().C;return"ON"===c||"on"===g.wF(a.videoData,"yt:cc")},$3=function(a,b){if(a.u&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.B||"FORCED_ON"===c.C},b4=function(a,b){if(a.B){if(a.K&&a.K.F)return a.K.F;
var c=b;c||(c=a.Za?!1:a.Ra?!1:!0);c=a.B.jl(c);for(var d=[a.videoData.captionsLanguagePreference,a.C.captionsLanguagePreference,g.wF(a.videoData,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(f3(c[f])===d[e])return c[f];return a.K&&a.K.D?a.K.D:(d=c.find(function(h){return h.isDefault}))?d:c[0]||a4(a)}return null},a4=function(a){return a.K&&a.K.B},c4=function(a){var b=a4(a);
return!!b&&a.u===b},NDa=function(a,b){for(var c=a.J.app.F.La().textTracks,d=a.u.toString(),e=0;e<c.length;e++){var f=c[e];
f.id===d&&(b?"showing"!==f.mode&&(f.mode="showing"):"showing"===f.mode&&(f.mode="disabled"))}},e4=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.ba=c,a.ba&&d4(a,"module-enabled",!!b));a.u=b;$3(a)&&(a.u=a4(a));a.load()},ODa=function(a,b){var c=a.Ma.getVideoContentRect(!0).height;
if(!c)return null;var d=a.u?a.u.languageCode:null;!b.params.u&&d&&LDa.test(d)&&(b.params.u=1);d=a.Ma.getPlayerSize();switch(null!=b.params.Wm?b.params.Wm:1<b.u.length?1:0){case 1:return new o3(b,a.D,a.I,c,d.width,d.height,a.C.experiments);case 2:return new p3(b,a.D,a.I,c,d.width,d.height,a.C.experiments);default:return new n3(b,a.D,a.I,c,d.width,d.height,a.C.experiments)}},W3=function(a,b,c){c=void 0===c?!1:c;
var d=f4.oc;a.D={};g.Wa(a.D,f4);a.D.oc={};g.Wa(a.D.oc,d);a.I={oc:{}};var e=b.backgroundOverride?a.I:a.D,f=b.background||d.background;y3.test(f);e.oc.background=f;e=b.colorOverride?a.I:a.D;f=b.color||d.color;y3.test(f);e.oc.color=f;e=b.windowColorOverride?a.I:a.D;f=b.windowColor||f4.windowColor;y3.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.I:a.D;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.oc.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.I:a.D;f=b.fontSizeIncrement;null==
f&&(f=d.fontSizeIncrement);e.oc.fontSizeIncrement=f;f=b.fontStyleOverride?a.I:a.D;e=b.fontStyle;null==e&&(e=d.bold&&d.Yg?3:d.bold?1:d.Yg?2:0);f=f.oc;switch(e){case 1:f.bold=!0;delete f.Yg;break;case 2:delete f.bold;f.Yg=!0;break;case 3:f.bold=!0;f.Yg=!0;break;default:delete f.bold,delete f.Yg}e=b.textOpacityOverride?a.I:a.D;f=b.textOpacity;null==f&&(f=d.textOpacity);e.oc.textOpacity=f;e=b.windowOpacityOverride?a.I:a.D;f=b.windowOpacity;null==f&&(f=f4.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?
a.I:a.D;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.oc.charEdgeStyle=f;e=b.fontFamilyOverride?a.I:a.D;f=b.fontFamily;null==f&&(f=d.fontFamily);e.oc.fontFamily=f;a.loaded&&a.Ry();c&&d4(a,"display-settings",b)},QDa=function(a,b){if(b&&!a.N){var c=mDa({u:0,
lang:"tr"});a.N=[c,new q3(c.start,c.end-c.start,0,c.id,"Altyaz\u0131lar \u015fu \u015fekilde g\u00f6r\u00fcn\u00fcr")];g.kM(a.player,a.N)}else!b&&a.N&&(PDa(a,a.N),a.N=null)},PDa=function(a,b){g.lM(a.player.app,b,void 0);
g.Gb(b,function(c){g.rb(this.X,c)},a);
a.Y.ub()},X3=function(a,b){if(!a.storage)return null;
try{var c=a.storage.get(b)}catch(d){a.storage.remove(b)}return c},d4=function(a,b,c){if(a.storage)try{a.storage.set(b,c)}catch(d){}};
g.IS.prototype.bo=g.ca(11,function(){for(var a=g.re(document,"track",void 0,this.u),b=0;b<a.length;b++)g.Je(a[b])});
g.JS.prototype.bo=g.ca(10,function(){this.u.bo()});
g.IS.prototype.cq=g.ca(9,function(){return!!this.u.textTracks});
g.JS.prototype.cq=g.ca(8,function(){return this.u.cq()});
g.IS.prototype.Tn=g.ca(7,function(a){for(var b=0;b<a.length;b++)this.u.appendChild(a[b])});
g.JS.prototype.Tn=g.ca(6,function(a){this.u.Tn(a)});
g.CS.prototype.Ul=g.ca(5,function(){});
g.IS.prototype.Ul=g.ca(4,function(){return!(!this.u.textTracks||!this.u.textTracks.addEventListener)});
g.JS.prototype.Ul=g.ca(3,function(){return this.u.Ul()});
g.Uv.prototype.Ir=g.ca(1,function(){return 0});
g.iz.prototype.Ir=g.ca(0,function(a){return(a=this.Kh(a))?a.u:0});
var LDa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i;VCa.prototype.jl=function(a){return a?this.u.concat(this.B):this.u};
g.u(h3,g.B);g.k=h3.prototype;g.k.jl=function(a){return this.B.jl(a)};
g.k.us=function(){};
g.k.ws=function(){};
g.k.vj=function(){};
g.k.Fm=function(){return""};
g.k.RE=function(){return!1};
g.k.aa=function(){this.vj();g.B.prototype.aa.call(this)};
g.u(i3,h3);i3.prototype.us=function(a,b,c){var d=this;this.la();b=this.Fm(a,b);this.vj();this.u=g.oq(b,{format:"RAW",onSuccess:function(e){d.u=null;c(e.responseText,a)},
withCredentials:!0})};
i3.prototype.ws=function(a){if(this.audioTrack)for(var b=g.q(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g3(this.B,c.value);a()};
i3.prototype.Fm=function(a,b){var c=a.cd(),d={fmt:b};if("srv3"===b||"3"===b||"json3"===b)g.ak()?Object.assign(d,{xorb:2,xobt:1,xovt:1}):Object.assign(d,{xorb:2,xobt:3,xovt:3});a.translationLanguage&&(d.tlang=f3(a));return g.Zp(c,d)};
i3.prototype.vj=function(){this.u&&this.u.abort()};
j3.prototype.contains=function(a){a=g.Ab(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
j3.prototype.length=function(){return this.segments.length/2};
g.u(k3,g.B);g.k=k3.prototype;g.k.aa=function(){g.B.prototype.aa.call(this);this.B&&this.B.cancel()};
g.k.UC=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.fc();var b=this.u;this.u=g.fb(this.W.Pi(a).u);b!==this.u&&this.N&&this.N()};
g.k.reset=function(){this.D=new j3;this.B&&(this.B.cancel(),this.B=null)};
g.k.tC=function(){this.la();var a;if(a=null!=this.u)a=this.u,a=a.u.gj(a);!a||this.B||this.u&&30<this.u.startTime-this.player.getCurrentTime()||(a=this.u.Oj(),a.u[0].duration?(this.D.contains(a.u[0].B)||YCa(this,a),this.u=g.fb(a.u)):!g.R(this.P.experiments,"force_caption_seek_for_live_killswitch")&&this.u&&this.u.I&&this.u.I+this.player.fc()<this.player.getCurrentTime()&&this.seekTo(this.player.getCurrentTime()));this.K.start()};
g.u(l3,h3);g.k=l3.prototype;g.k.us=function(a,b,c){var d=this;this.vj();b=$Ca(this,a.getId());b||(b=a.languageCode,b=this.ma.isManifestless?aDa(this,b,"386"):aDa(this,b));if(b){var e=1E3*(b.index.Ir(b.index.Qg())-b.index.oe(b.index.Qg()));this.u=new k3(new g.Su,this.J,b,function(f,h){c(f,a,h,e)},this.F||g.Iu(b.info),function(){d.u&&d.u.reset();
d.C=!0})}};
g.k.RE=function(){var a=this.C;this.C=!1;return a};
g.k.ws=function(a){var b;this.F?b=[new g.sE({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.sE({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:b=this.ma.isManifestless?ZCa(this,"386"):ZCa(this);b=g.q(b);for(var c=b.next();!c.done;c=b.next())g3(this.B,c.value);a()};
g.k.vj=function(){this.u&&(this.u.dispose(),this.u=null)};
g.k.Fm=function(){return""};
g.u(m3,h3);m3.prototype.us=function(a,b,c){var d=this;this.la();b=this.Fm(a,b);this.vj();this.u=g.oq(b,{format:"RAW",onSuccess:function(e){d.u=null;c(e.responseText,a)},
withCredentials:!0})};
m3.prototype.ws=function(a){var b=this,c=this.C,d={type:"list",tlangs:1,v:this.videoId,vssids:1};this.TB&&(d.asrs=1);c=g.Zp(c,d);this.vj();this.u=g.oq(c,{format:"RAW",onSuccess:function(e){b.u=null;if((e=e.responseXML)&&e.firstChild){for(var f=e.getElementsByTagName("track"),h=0;h<f.length;h++){var l=f[h],m=l.getAttribute("lang_code"),n=l.getAttribute("lang_translated"),p=l.getAttribute("name"),r=l.getAttribute("kind"),t=l.getAttribute("id"),w="true"===l.getAttribute("lang_default"),x="true"===l.getAttribute("cantran");
l=l.getAttribute("vss_id");g3(b.B,new g.sE({languageCode:m,languageName:n,name:p,kind:r,id:t,is_servable:!0,is_translateable:x,vss_id:l,is_default:w}))}e=e.getElementsByTagName("target");f=e.length;for(h=0;h<f;h++)m={languageCode:e[h].getAttribute("lang_code"),languageName:e[h].getAttribute("lang_translated"),languageOriginal:e[h].getAttribute("lang_original"),id:e[h].getAttribute("id"),isDefault:"true"===e[h].getAttribute("lang_default")},b.F[m.languageCode]=m.languageName,b.D.push(m)}a()},
withCredentials:!0})};
m3.prototype.Fm=function(a,b){var c=this.C,d={v:this.videoId,type:"track",lang:a.languageCode,name:a.getName(),kind:a.kind,fmt:b};a.translationLanguage&&(d.tlang=f3(a));return c=g.Zp(c,d)};
m3.prototype.vj=function(){this.u&&this.u.abort()};
var y3=/^#(?:[0-9a-f]{3}){1,2}$/i;var cDa=["left","right","center","justify"];g.u(n3,g.V);g.k=n3.prototype;g.k.FK=function(a,b){var c=g.Cg(this.element,this.element.parentElement);this.xa=a-c.x;this.Fa=b-c.y;g.I(this.element,"ytp-dragging")};
g.k.EK=function(a,b){var c=g.Eg(this.element),d=a-this.xa-.02*this.playerWidth,e=b-this.Fa-.02*this.playerHeight,f=(d+c.width/2)/this.maxWidth*3;f=Math.floor(g.be(f,0,2));var h=(e+c.height/2)/this.Ia*3;h=Math.floor(g.be(h,0,2));var l=f+3*h;d=(d+f/2*c.width)/this.maxWidth;d=100*g.be(d,0,1);c=(e+h/2*c.height)/this.Ia;c=100*g.be(c,0,1);this.B.params.Hg=l;this.B.params.wh=c;this.B.params.Tf=d;this.u.Hg=l;this.u.wh=c;this.u.Tf=d;this.xF()};
g.k.DK=function(){g.Bn(this.element,"ytp-dragging")};
g.k.xF=function(){this.Ql(this.F)};
g.k.Ql=function(a){var b=Math.min(this.nB(),this.maxWidth),c=this.mB(),d="";3===this.B.params.u&&(d="rotate(180deg)");g.F(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.Vu(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.u.Tf+2;d=this.u.Hg;switch(d){case 0:case 3:case 6:b=this.u.oc.fontSizeIncrement;!g.R(this.experiments,"web_player_ignore_left_percentage_for_large_font_killswitch")&&
b&&2<b&&2!==this.u.u&&3!==this.u.u&&(e=2);a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.D.offsetWidth;b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.u.wh+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-
b+"%"}g.F(this.element,a)};
g.k.Vu=function(a){var b;for(b=0;b<a.length&&a[b]===this.F[b];b++);if(this.Y||this.F.length>b)b=0,this.Y=!1,this.F=[],this.I=this.fa=this.ba=null,g.He(this.D);for(;b<a.length;b++)gDa(this,a[b])};
g.k.nB=function(){return 0};
g.k.mB=function(){return 0};
g.k.toString=function(){return g.V.prototype.toString.call(this)};g.u(o3,n3);o3.prototype.Vu=function(a){var b=this.B.u;n3.prototype.Vu.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.u===e)var d=f;else{d={};g.Wa(d,c.u);g.Wa(d,RDa);var e=c.u;var f=d}gDa(this,c,d)}};
var RDa={gJ:!0};g.u(p3,n3);g.k=p3.prototype;g.k.xF=function(){g.tn(this.ka)};
g.k.JO=function(){g.Bn(this.element,"ytp-rollup-mode");this.Ql(this.jb,!0)};
g.k.mB=function(){return this.C?this.W:this.P};
g.k.nB=function(){return this.C?this.P:this.W};
g.k.Ql=function(a,b){this.jb=a;if(this.B.params.B){for(var c=0,d=0;d<this.F.length&&c<a.length;d++)this.F[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.F.concat(a.slice(c)));this.Ma=this.W;this.P=this.W=0;n3.prototype.Ql.call(this,a);lDa(this,b);n3.prototype.Ql.call(this,a)}else n3.prototype.Ql.call(this,a)};g.u(q3,g.oD);q3.prototype.toString=function(){return g.oD.prototype.toString.call(this)};g.u(r3,g.oD);r3.prototype.toString=function(){return g.oD.prototype.toString.call(this)};
var s3=0;g.u(t3,g.B);t3.prototype.C=function(){return[]};
t3.prototype.reset=function(){};g.u(u3,t3);u3.prototype.reset=function(){this.N={};this.B=this.u=null;this.K=!0};
u3.prototype.C=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.q(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1===d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.q(e),c=e.next();!c.done;c=e.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var h=this.D,l={},m=c.getAttribute("p");m&&g.Wa(l,this.D[m]);m=w3(c,"b");null!=m&&
(l.bold=m);m=w3(c,"i");null!=m&&(l.Yg=m);m=w3(c,"u");null!=m&&(l.underline=m);m=x3(c,"et");null!=m&&(l.charEdgeStyle=m);m=x3(c,"of");null!=m&&(l.offset=m);m=z3(c,"bc");null!=m&&(l.background=m);m=z3(c,"ec");null!=m&&(l.hv=m);m=z3(c,"fc");null!=m&&(l.color=m);m=x3(c,"fs");null!=m&&0!==m&&(l.fontFamily=m);m=v3(c,"sz");void 0!==m&&(l.fontSizeIncrement=m/100-1);m=v3(c,"bo");void 0!==m&&(l.backgroundOpacity=m/255);m=v3(c,"fo");void 0!==m&&(l.textOpacity=m/255);m=x3(c,"rb");null!=m&&10!==m&&0!==m&&(l.Sc=
10<m?m-1:m);c=x3(c,"hg");null!=c&&(l.QB=c);h[d]=l;break;case "ws":d=c.getAttribute("id");this.W[d]=pDa(this,c);break;case "wp":d=c.getAttribute("id"),this.P[d]=qDa(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.q(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1===d.nodeType)switch(d.tagName){case "w":this.u=rDa(this,d,e,!1);(d=this.N[this.u.id])&&d.end>this.u.start&&(d.end=this.u.start);this.N[this.u.id]=this.u;c.push(this.u);break;case "p":var n=e;h=[];l=d.getAttribute("w")||this.F;m=!!w3(d,
"a");n=(v3(d,"t")||0)+n;var p=v3(d,"d")||5E3;m||(!this.K&&this.B&&this.B.windowId===l&&this.B.end>n&&(this.B.end=n),this.B&&"\n"===this.B.text&&(this.B.text=""));var r=m?6:5,t=d.getAttribute("p");t=t?this.D[t]:null;var w=Array.from(d.childNodes);w.length&&(this.K=null!=d.getAttribute("d"));for(var x=0;x<w.length;x++){var y=w[x],D=void 0;0<x&&(m=!0);var E=void 0;1===y.nodeType&&(E=y);if(E&&"s"===E.tagName){if((y=(y=E.getAttribute("p"))?this.D[y]:null)&&y.Sc&&(1===y.Sc?(y=w.slice(x,x+4),4===y.length&&
(D=oDa(n,p,l,m,r,y,this.D),x+=3)):D=oDa(n,p,l,m,r,[E],this.D)),!D){var G=E;D=n;E=p;y=l;var K=m,M=r,Ia=G.textContent?G.textContent:"",va=G.getAttribute("p");va=va?this.D[va]:null;G=v3(G,"t")||0;D=new q3(D+G,E-G,M,y,Ia,K,va)}}else D=new q3(n,p,r,l,y.textContent||"",m,t);h.push(D);this.B=D}if(0<h.length)for(h[0].windowId===this.F&&(this.u=rDa(this,d,e,!0),c.push(this.u)),d=g.q(h),h=d.next();!h.done;h=d.next())h=h.value,h.windowId=this.u.id,this.u.u.push(h),c.push(h)}e=c}else e=[];return e};var SDa=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.u(A3,t3);A3.prototype.reset=function(){this.B.clear()};
A3.prototype.C=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens)for(var d=0,e=g.q(c.pens),f=e.next();!f.done;f=e.next()){f=f.value;var h={},l=f.pParentId;l&&Object.assign(h,this.u.get(l));f.bAttr&&(h.bold=!0);f.iAttr&&(h.Yg=!0);f.uAttr&&(h.underline=!0);l=f.ofOffset;null!=l&&(h.offset=l);void 0!==f.szPenSize&&(h.fontSizeIncrement=f.szPenSize/100-1);l=f.etEdgeType;null!=l&&(h.charEdgeStyle=l);void 0!==f.ecEdgeColor&&(h.hv=B3(f.ecEdgeColor));l=f.fsFontStyle;null!=l&&0!==l&&(h.fontFamily=l);
void 0!==f.fcForeColor&&(h.color=B3(f.fcForeColor));void 0!==f.foForeAlpha&&(h.textOpacity=f.foForeAlpha/255);void 0!==f.bcBackColor&&(h.background=B3(f.bcBackColor));void 0!==f.boBackAlpha&&(h.backgroundOpacity=f.boBackAlpha/255);(l=f.rbRuby)&&10!==l&&(h.Sc=10<l?l-1:l,h.rh=SDa.get(h.Sc));f.hgHorizGroup&&(h.QB=f.hgHorizGroup);this.u.set(d++,h)}if(c.wsWinStyles)for(d=0,e=g.q(c.wsWinStyles),f=e.next();!f.done;f=e.next())f=f.value,h={},(l=f.wsParentId)?Object.assign(h,this.F.get(l)):Object.assign(h,
this.I),void 0!==f.mhModeHint&&(h.Wm=f.mhModeHint),void 0!==f.juJustifCode&&(h.textAlign=f.juJustifCode),void 0!==f.pdPrintDir&&(h.u=f.pdPrintDir),void 0!==f.sdScrollDir&&(h.C=f.sdScrollDir),void 0!==f.wfcWinFillColor&&(h.windowColor=B3(f.wfcWinFillColor)),void 0!==f.wfoWinFillAlpha&&(h.windowOpacity=f.wfoWinFillAlpha/255),this.F.set(d++,h);if(c.wpWinPositions)for(d=0,e=g.q(c.wpWinPositions),f=e.next();!f.done;f=e.next())f=f.value,h={},(l=f.wpParentId)&&Object.assign(h,this.D.get(l)),void 0!==f.ahHorPos&&
(h.Tf=f.ahHorPos),void 0!==f.apPoint&&(h.Hg=f.apPoint),void 0!==f.avVerPos&&(h.wh=f.avVerPos),void 0!==f.ccCols&&(h.Gj=f.ccCols),void 0!==f.rcRows&&(h.B=f.rcRows),this.D.set(d++,h);if(c.events)for(d=[],c=g.q(c.events),e=c.next();!e.done;e=c.next()){var m=e.value;e=(m.tStartMs||0)+b;f=m.dDurationMs||0;if(m.id)h=String(m.id),e=sDa(this,m,e,f,h),d.push(e),this.B.set(h,e);else{m.wWinId?h=m.wWinId.toString():(h="_"+s3++,l=sDa(this,m,e,f,h),d.push(l),this.B.set(h,l));0===f&&(f=5E3);l=this.B.get(h);var n=
!!m.aAppend,p=n?6:5,r=m.segs,t=null;m.pPenId&&(t=this.u.get(m.pPenId));for(m=0;m<r.length;m++){var w=r[m],x=w.utf8;if(x){var y=w.tOffsetMs||0,D=null;w.pPenId&&(D=this.u.get(w.pPenId));if(2===(null!=l.params.Wm?l.params.Wm:1<l.u.length?1:0)&&n&&"\n"===x)continue;if(w=D&&1===D.Sc)if(w=m,w+3>=r.length||!r[w+1].pPenId||!r[w+2].pPenId||!r[w+3].pPenId)w=!1;else{var E=r[w+1].pPenId;(E=this.u.get(E))&&E.Sc&&2===E.Sc?(E=r[w+2].pPenId,E=this.u.get(E),!E||!E.Sc||3>E.Sc?w=!1:(E=r[w+3].pPenId,w=(E=this.u.get(E))&&
E.Sc&&2===E.Sc?!0:!1)):w=!1}if(w){y=r[m+1].utf8;w=r[m+3].utf8;E=r[m+2].utf8;var G=this.u.get(r[m+2].pPenId);x=nDa(x,y,E,w,G);n=new q3(e,f,p,h,x,n,D);m+=3}else n=new q3(e+y,f-y,p,l.id,x,n,D||t);n&&(d.push(n),l.u.push(n))}n=!0}}}else d=[];return d};D3.prototype.clear=function(){this.C=this.time=this.mode=0;this.u=[];this.reset()};
D3.prototype.reset=function(){this.mode=0;this.D.reset(0);this.F.reset(1)};
var tDa=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];E3.prototype.set=function(a){this.type=a};
E3.prototype.get=function(){return this.type};
F3.prototype.clear=function(){this.state=0};
F3.prototype.update=function(){this.state=2===this.state?1:0};
F3.prototype.isValid=function(){return 0!==this.state};
F3.prototype.matches=function(a,b){return this.isValid()&&a===this.Lk&&b===this.Dj};
yDa.prototype.reset=function(){this.timestamp=this.u=0};
G3.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.C[b][c].timestamp=a};
G3.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.C[b][c];a=0===d.u?a+"_":a+String.fromCharCode(d.u)}a+="\n"}return a};
G3.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.C[b][c].reset();this.D=a;this.u=0;this.B=this.row=1};
var zDa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],ADa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],BDa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],CDa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];M3.prototype.reset=function(a,b){this.F=b;this.style.set(2);this.B=this.I;this.D=this.K;this.u=this.B;var c=(a<<2)+(b<<1);this.I.reset(c);this.K.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
C3.prototype.reset=function(a){this.F=a;this.u.clear();this.D=this.C;this.C.reset(a,0);this.I.reset(a,1)};HDa.prototype.F=function(){};g.u(O3,HDa);O3.prototype.F=function(a,b,c,d,e){if(c<d){var f="_"+s3++;c=c/1E3-this.K;d=d/1E3-this.K;a=new r3(c,d-c,5,f,{textAlign:0,Hg:0,Tf:2.5*b,wh:5.33*a});e=new q3(c,d-c,5,f,e);this.C.push(a);this.C.push(e)}};
g.u(R3,t3);R3.prototype.C=function(a){a=new O3(a,a.byteLength,this.B);if(IDa(a)){for(;a.u<a.B.byteLength;)for(0===a.version?a.D=Q3(a)*(1E3/45):1===a.version&&(a.D=4294967296*Q3(a)+Q3(a)),a.I=P3(a);0<a.I;a.I--){var b=P3(a),c=P3(a),d=P3(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.u,b.u.push({time:a.D,type:this.track,nA:c,oA:d,order:b.u.length}))}xDa(this.u,a);return a.C}return[]};
R3.prototype.reset=function(){this.u.clear()};g.u(T3,t3);
T3.prototype.C=function(a,b){for(var c=[],d=a.split(TDa),e=1;e<d.length;e++){var f=d[e],h=b;if(""!==f&&!UDa.test(f)){var l=g4.exec(f);if(l&&4<=l.length){var m=U3(l[1]),n=U3(l[2])-m;m+=h;var p=(l=l[3])?l.split(" "):[];l={};var r=null,t="",w=null,x="";l.textAlign=2;p=g.q(p);for(var y=p.next();!y.done;y=p.next())if(y=y.value.split(":"),2===y.length){var D=y[1];switch(y[0]){case "line":y=D.split(",");y[0].endsWith("%")&&(r=y[0],l.wh=Number.parseInt(r,10),2===y.length&&(t=y[1].trim()));break;case "position":y=
D.split(",");w=y[0];l.Tf=Number.parseInt(w,10);2===y.length&&(x=y[1].trim());break;case "align":switch(D){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}r||(l.wh=100,t||(t="end"));if(!w)switch(l.textAlign){case 0:l.Tf=0;break;case 1:l.Tf=100;break;default:l.Tf=50}r=0;switch(t){case "center":r+=3;break;case "end":r+=6;break;default:r+=0}switch(x){case "line-left":r+=0;break;case "center":r+=1;break;case "line-right":r+=2;break;default:switch(l.textAlign){case 0:r+=
0;break;case 2:r+=1;break;case 1:r+=2}}l.Hg=0>r||8<r?7:r;f=f.substring(g4.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");x=l;l=f;f={};if(0>l.indexOf("<")&&0>l.indexOf("&"))h=KDa(m,n,5,x),n=new q3(m,n,5,h.id,l,!1,g.Wb(f)?void 0:f),c.push(h),c.push(n),h.u.push(n);else for(t=l.split(VDa),1===t.length?(l=5,x=KDa(m,n,l,x)):(r=l=6,x=Object.assign({Gj:32},x),x=new r3(m,n,r,"_"+s3++,x)),c.push(x),r=m,w=0;w<t.length;w++)p=t[w],0===w%2?(y=g.V0("<html>"+p+"</html>"),y.getElementsByTagName("parsererror").length?
(D=y.createElement("span"),D.appendChild(y.createTextNode(p))):D=y.firstChild,JDa(this,r,n-(r-m),l,x,0<w,D,f,c)):r=U3(p)+h}g4.lastIndex=0}}return c};
var UDa=/^NOTE/,TDa=/(?:\r\n|\r|\n){2,}/,g4=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),VDa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.u(V3,g.B);V3.prototype.clear=function(){this.u&&this.u.dispose();this.u=null};
V3.prototype.reset=function(){this.u&&this.u.reset()};
V3.prototype.aa=function(){g.B.prototype.aa.call(this);this.clear()};var f4={windowColor:"#080808",windowOpacity:0,textAlign:2,Hg:7,Tf:50,wh:100,oc:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.u(Y3,g.vS);g.k=Y3.prototype;g.k.aa=function(){if(this.F||this.W){var a=this.J.app.F;a&&!a.la()&&a.bo()}else QDa(this,!1);g.vS.prototype.aa.call(this)};
g.k.load=function(){var a=this;g.vS.prototype.load.call(this);var b=!g.R(this.C.experiments,"web_player_captions_track_list_changed_killswitch");this.K=this.player.getAudioTrack();if(this.B)this.u&&(this.oa.clear(),this.F?NDa(this,!0):3!==this.player.getPresentingPlayerType()&&this.B.us(this.u,"json3",function(d,e,f,h){if(d){a.B.RE()&&(a.X=[],g.aX(a.J,"captions"),a.Y.ub(),a.oa.reset());var l=a.oa;f=f||0;h=h||0;if(l.B.ca("html5_disable_rawcc_killswitch")){if("string"!==typeof d){var m=new DataView(d);
8<=m.byteLength&&1718909296===m.getUint32(4)&&(m=g.qt(m,0,1835295092),d=d.slice(m.dataOffset,m.dataOffset+m.size),S3(d)||(d=g.We(new Uint8Array(d))))}}else"string"===typeof d||S3(d)||(m=new DataView(d),d=8>=m.byteLength||1718909296!==m.getUint32(4)?"":(m=g.qt(m,0,1835295092))&&m.size?g.We(new Uint8Array(d.slice(m.dataOffset,m.dataOffset+m.size))):"");if(d)try{if("string"!==typeof d){var n=d,p=f,r=h;if(!S3(n))throw Error("Invalid binary caption track data");l.u||(l.u=new R3(r,e));var t=l.u.C(n,p)}else{if("WEBVTT"===
d.substring(0,6))e=d,r=f,l.u||(l.u=new T3),p=l.u.C(e,r),.01>Math.random()&&g.er(Error("Deprecated subtitles format in web player: WebVTT")),n=p;else b:{p=d;if("{"===p[0])try{l.u||(l.u=new A3(MDa(e)));n=l.u.C(p,f);break b}catch(G){g.dr(G);n=[];break b}r=g.V0(p);if(!r||!r.firstChild){var w=Error("Invalid caption track data");w.params=p;throw w;}if("timedtext"===r.firstChild.tagName){if(3===Number(r.firstChild.getAttribute("format"))){l.u||(l.u=new u3(MDa(e),l.B));n=l.u.C(r,f);break b}var x=Error("Unsupported subtitles format in web player (Format2)");
x.params=p;throw x;}if("transcript"===r.firstChild.tagName){var y=Error("Unsupported subtitles format in web player (Format1)");y.params=p;throw y;}var D=Error("Invalid caption track data");D.params=p;throw D;}t=n}var E=t}catch(G){g.dr(G),l.clear(),E=[]}else E=[];g.kM(a.player,E);!a.ba||a.W||c4(a)||g.VB(a.C)||g.WB(a.C)||(a.ea.lg(),E=mDa({Hg:0,Tf:5,wh:5,B:2,textAlign:0,u:0,lang:"tr"}),a.ha=[E],l=["Ayarlar i\u00e7in "," simgesini t\u0131klay\u0131n"],a.xa||(t=new g.zM(g.jN()),g.C(a,t),a.xa=t.element),
t=E.end-E.start,(e=g.tE(a.u))&&a.ha.push(new q3(E.start,t,0,E.id,e)),a.ha.push(new q3(E.start,t,0,E.id,l[0]),new q3(E.start,t,0,E.id,a.xa,!0),new q3(E.start,t,0,E.id,l[1],!0)),g.kM(a.player,a.ha),a.ea.ub());!a.ba||a.W||c4(a)||(d4(a,"module-enabled",!0),a.K&&(a.K.F=a.u),(E=g.Z(a.player.app))&&g.RT(E.I));a.ba=!1}}),!b||this.F||this.W||c4(this)||this.player.va("captionschanged",e3(this.u))),b||(this.u&&!c4(this)?this.player.va("captionschanged",e3(this.u)):this.player.va("onCaptionsTrackListChanged"));
else{var c;this.Fa?c=new l3(this.videoData.ma,this.player):this.Ra?c=new i3(this.C,this.videoData,this.player.getAudioTrack()):c=new m3(this.videoData.Zn,this.videoData.videoId,this.videoData.captionsLanguagePreference||this.C.captionsLanguagePreference||g.wF(this.videoData,"yt:cc_default_lang")||this.C.ce,this.videoData.dv,this.C);this.B=c;g.C(this,this.B);c.ws(function(){var d;a.ba||Z3(a)?d=b4(a,a.ba):$3(a)&&(d=a4(a));if(a.F||a.W){for(var e=a.B.jl(!0),f=[],h=0;h<e.length;h++){var l=e[h],m=g.Ee("TRACK");
m.setAttribute("kind","subtitles");m.setAttribute("label",g.tE(l));m.setAttribute("srclang",f3(l));m.setAttribute("id",l.toString());a.W||m.setAttribute("src",a.B.Fm(l,"vtt"));l===d&&m.setAttribute("default","1");f.push(m)}d=a.J.app.F;d.Tn(f);f=d.La();a.Ia&&a.fa.R(f.textTracks,"change",a.kP)}else!a.u&&d&&e4(a,d),a.player.va("onCaptionsTrackListChanged"),a.player.va("onApiChange")})}};
g.k.unload=function(){this.F&&this.u?NDa(this,!1):(this.ea&&this.ea.lg(),g.aX(this.player,"captions"),this.X=[],this.B&&this.B.vj(),this.oa.clear(),this.N&&g.kM(this.player,this.N),this.Ry());g.vS.prototype.unload.call(this);var a=g.Z(this.player.app);a&&g.RT(a.I);this.player.va("captionschanged",{})};
g.k.create=function(){(this.ya?this.F||this.W:$3(this)||Z3(this))&&this.load()};
g.k.kP=function(){for(var a=this.J.app.F.La().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=a[c].id;for(var d=this.B.jl(!0),e=0;e<d.length;e++)if(d[e].toString()===b){b=d[e];break a}b=null}(this.loaded?this.u:null)!==b&&e4(this,b,!0)};
g.k.RQ=function(){!this.u&&this.F||this.unload()};
g.k.GK=function(a){this.X.push(a);this.Y.ub()};
g.k.HK=function(a){g.rb(this.X,a);this.B instanceof l3&&this.B.F&&g.lM(this.player.app,[a],void 0);this.Y.ub()};
g.k.ZP=function(a){if(a instanceof r3){var b=this.P[a.id];b&&b.B!==a&&(b.dispose(),delete this.P[a.id],b=null);b||(b=ODa(this,a))&&(this.P[a.id]=b)}else b=a.windowId,this.ka[b]||(this.ka[b]=[]),this.ka[b].push(a)};
g.k.gQ=function(){PDa(this,this.ha);this.ha=null};
g.k.gG=function(){var a=this;this.Y.stop();g.Xb(this.ka);this.X.sort(g.qD);var b=this.X;if(this.N){var c=g.Ke(b,function(d){return-1===this.N.indexOf(d)},this);
c.length&&(b=c)}g.Gb(b,this.ZP,this);g.Jb(this.P,function(d,e){a.ka[e]?(d.element.parentNode||(d instanceof p3||d instanceof o3||g.Mb(a.P,function(f,h){h!==e&&f.B.params.Hg===d.B.params.Hg&&f.B.params.Tf===d.B.params.Tf&&f.B.params.wh===d.B.params.wh&&(f.dispose(),delete a.P[h]);return h===e},a),g.$O(a.player,d.element,4)),d.Ql(a.ka[e])):(d.dispose(),delete a.P[e])},this)};
g.k.kQ=function(){W3(this,{},!0);g.R(this.C.experiments,"web_player_disable_publish_captions_settings_changed_on_reset")||this.player.va("captionssettingschanged")};
g.k.zI=function(){var a=f4.oc;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.Yg?3:a.bold?1:a.Yg?2:0,textOpacity:a.textOpacity,windowColor:f4.windowColor,windowOpacity:f4.windowOpacity};var b=X3(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.nG=function(a,b){var c={};g.Wa(c,X3(this,"display-settings"));g.Wa(c,a);W3(this,c,b);this.player.va("captionssettingschanged")};
g.k.Ry=function(){!this.F&&this.loaded&&(g.Jb(this.P,function(a,b){a.dispose();delete this.P[b]},this),this.gG())};
g.k.Rd=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.be(b,-2,4);this.nG({fontSizeIncrement:c});return c;case "reload":b&&!this.F&&e4(this,this.u,!0);break;case "stickyLoading":void 0!==b&&this.C.C&&d4(this,"module-enabled",!!b);break;case "track":if(!this.B)return{};if(b){if(this.F)break;if(!g.Sa(b))break;if(g.Wb(b)){e4(this,null,!0);break}for(var d=this.B.jl(!0),e=0;e<d.length;e++){var f=d[e];f.languageCode!==b.languageCode||c&&f.languageName!==b.languageName||(c=b.translationLanguage?
UCa(f,b.translationLanguage):f)}!c||c===this.u&&this.loaded||e4(this,c,!0)}else return this.loaded&&this.u&&!c4(this)?e3(this.u):{};return"";case "tracklist":return this.B?g.Pc(this.B.jl(!(!b||!b.includeAsr)),function(h){return e3(h)}):[];
case "translationLanguages":return this.B?this.B.D.map(function(h){return Object.assign({},h)}):[];
case "sampleSubtitles":this.F||void 0===b||QDa(this,!!b)}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.C.C&&a.push("stickyLoading");return a};
g.k.DJ=function(){var a=this.u;return a?{cc:a.vssId}:{}};
g.k.IQ=function(){this.loaded&&this.u&&!c4(this)?(d4(this,"module-enabled",!1),this.unload(),$3(this,!0)&&e4(this,a4(this),!1)):e4(this,c4(this)||!this.u?b4(this,!0):this.u,!0)};
g.k.wM=function(){var a=c4(this);$3(this,a)?e4(this,this.player.getAudioTrack().B,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),(this.ya?this.F||this.W:$3(this)||Z3(this))&&(a?e4(this,b4(this),!1):this.load()))};g.oX.captions=Y3;})(_yt_player);
